Q1. Write a program to distinguish between Array Indexing and Fancy Indexing.

In [6]:
import numpy as np

arr=np.array([1,2,3,4,5,6,7,8,9,0])

#Normal indexing is just displaying one element in an array by giving the index value in the print statement
simple = arr[3]
print("Simple Indexing: " , simple)

#Fancy indexing is where we can display multiple elements at once from an array by giving multiple values in one print statement
fancy=arr[[1,4,7,9]]
print("Fancy indexing:" , fancy)

Simple Indexing:  4
Fancy indexing: [2 5 8 0]


Q2. Execute the 2D array Slicing.

In [7]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr)
print("-----------------------------------------------------")
print(arr[0, 0:2])
print("-----------------------------------------------------")
print(arr[0:1,2])
print("-----------------------------------------------------")

[[1 2 3 4]
 [5 6 7 8]]
-----------------------------------------------------
[1 2]
-----------------------------------------------------
[3]
-----------------------------------------------------


Q3. Create the 5-Dimensional arrays using ‘ndmin’.

In [9]:
arr= np.array([1,2,3,4,5], ndmin=5)

print("arr:",arr)

arr: [[[[[1 2 3 4 5]]]]]


Q4. Reshape the array from 1-D to 2-D array.

In [12]:
arr=np.array([1,2,3,4,5,6,7,8,9,0])

print("Original array:",arr)

res_arr= arr.reshape(5,2)

print("New array after reshaping : \n", res_arr)

Original array: [1 2 3 4 5 6 7 8 9 0]
New array after reshaping : 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]
 [9 0]]


Q5. Perform the Stack functions in Numpy arrays – Stack(), hstack(), vstack(), and dstack().

In [15]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr_res1 = np.hstack((arr1, arr2))

print("Vorizontal stack: \n",arr_res1)

arr_res2 = np.vstack((arr1, arr2))

print("\n Vertical stack:\n",arr_res2)

arr_res3 = np.dstack((arr1, arr2))

print("\n dstack:\n", arr_res3)

arr_res4 = np.stack((arr1, arr2), axis=1)

print("\n Normal stack:\n",arr_res4)

Vorizontal stack: 
 [1 2 3 4 5 6]

 Vertical stack:
 [[1 2 3]
 [4 5 6]]

 dstack:
 [[[1 4]
  [2 5]
  [3 6]]]

 Normal stack:
 [[1 4]
 [2 5]
 [3 6]]


Q6. Perform the searchsort method in Numpy array.

In [ ]:
arr = np.array([6, 8, 9,7])

x = np.searchsorted(arr, 7,side='left')

print(x)

Q7. Create Numpy Structured array using your domain features.

In [ ]:
import numpy as np

# Define the structured data type for the election system
election_dtype = np.dtype([
    ('voter_id', 'int32'),
    ('voter_name', 'U50'),  # 'U50' specifies Unicode string of up to 50 characters
    ('age', 'int32'),
    ('address', 'U100'),   # 'U100' specifies Unicode string of up to 100 characters
    ('vote_cast', 'bool')
])

# Create a structured array with sample data
election_data = np.array([
    (1, 'Alok Misra', 30, '123 Main St', True),
    (2, 'John Smith', 28, '456 Elm St', False),
    (3, 'Anand Patel', 35, '789 Oak St', True)
], dtype=election_dtype)

# Print the structured array
print("Election Data Structured Array:")
print(election_data)

Q8. Create Data frame using List and Dictionary.

In [1]:
pip install pandas


Defaulting to user installation because normal site-packages is not writeable
  Obtaining dependency information for pandas from https://files.pythonhosted.org/packages/ee/70/bad32e3c05d95bc53ed2c596fc8edb333cdd9049d248b6702d92d6be2389/pandas-2.1.0-cp39-cp39-macosx_11_0_arm64.whl.metadata
  Obtaining dependency information for pytz>=2020.1 from https://files.pythonhosted.org/packages/32/4d/aaf7eff5deb402fd9a24a1449a8119f00d74ae9c2efa79f8ef9994261fc2/pytz-2023.3.post1-py2.py3-none-any.whl.metadata
  Using cached pytz-2023.3.post1-py2.py3-none-any.whl.metadata (22 kB)
  Using cached tzdata-2023.3-py2.py3-none-any.whl (341 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.3/11.3 MB 1.7 MB/s eta 0:00:0000:0100:01
Using cached pytz-2023.3.post1-py2.py3-none-any.whl (502 kB)
Note: you may need to restart the kernel to use updated packages.


In [1]:
import pandas as pd

# Creating a DataFrame using Lists
multimedia_data = [
    {
        "id": 1,
        "type": "image",
        "url": "https://example.com/image1.jpg",
        "title": "Image 1",
        "description": "This is the first image.",
    },
    {
        "id": 2,
        "type": "video",
        "url": "https://example.com/video1.mp4",
        "title": "Video 1",
        "description": "This is the first video.",
    },
    {
        "id": 3,
        "type": "audio",
        "url": "https://example.com/audio1.mp3",
        "title": "Audio 1",
        "description": "This is the first audio.",
    },
]

# Create a DataFrame from the list of multimedia data
multimedia_df = pd.DataFrame(multimedia_data)

# Print the DataFrame
print(multimedia_df)
   

   id   type                             url    title  \
0   1  image  https://example.com/image1.jpg  Image 1   
1   2  video  https://example.com/video1.mp4  Video 1   
2   3  audio  https://example.com/audio1.mp3  Audio 1   

                description  
0  This is the first image.  
1  This is the first video.  
2  This is the first audio.  


Q9. Create Data frame on your Domain area and perform the following operations to find and eliminate the
missing data from the dataset.
• isnull()
• notnull()
• dropna()
• fillna()
• replace()
• interpolate()

In [3]:
import pandas as pd

# Create a list of multimedia data
multimedia_data = [
    {
        "id": 1,
        "type": "image",
        "url": "https://example.com/image1.jpg",
        "title": "Image 1",
        "description": "This is the first image.",
    },
    {
        "id": 2,
        "type": "video",
        "url": "https://example.com/video1.mp4",
        "title": "Video 1",
        "description": "This is the first video.",
    },
    {
        "id": 3,
        "type": "audio",
        "url": "https://example.com/audio1.mp3",
        "title": "Audio 1",
        "description": "This is the first audio.",
    },
    {
        "id": 4,
        "type": "image",
        "url": "https://example.com/image2.jpg",
        "title": "Image 2",
        "description": "This is the second image.",
    },
    {
        "id": 5,
        "type": "video",
        "url": "https://example.com/video2.mp4",
        "title": "Video 2",
        "description": None,  # Missing data
    },
    {
        "id": 6,
        "type": "audio",
        "url": "https://example.com/audio2.mp3",
        "title": "Audio 2",
        "description": None,  # Missing data
    },
]

# Create a DataFrame from the list of multimedia data
multimedia_df = pd.DataFrame(multimedia_data)

# Identify the missing data
print(multimedia_df.isnull())

# Drop the missing data
multimedia_df = multimedia_df.dropna()

# Fill in the missing data
multimedia_df = multimedia_df.fillna("Unknown")

# Replace the missing data
multimedia_df = multimedia_df.replace("None", "NA")

# Interpolate the missing data
multimedia_df = multimedia_df.interpolate()

# Print the DataFrame
print(multimedia_df)






      id   type    url  title  description
0  False  False  False  False        False
1  False  False  False  False        False
2  False  False  False  False        False
3  False  False  False  False        False
4  False  False  False  False         True
5  False  False  False  False         True
   id   type                             url    title  \
0   1  image  https://example.com/image1.jpg  Image 1   
1   2  video  https://example.com/video1.mp4  Video 1   
2   3  audio  https://example.com/audio1.mp3  Audio 1   
3   4  image  https://example.com/image2.jpg  Image 2   

                 description  
0   This is the first image.  
1   This is the first video.  
2   This is the first audio.  
3  This is the second image.  


/var/folders/cp/5711s1d55n95y8r5m7tv2plw0000gn/T/ipykernel_8042/991806757.py:65: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  multimedia_df = multimedia_df.interpolate()


Q10. Perform the Hierarchical Indexing in the above created dataset.

In [7]:
import pandas as pd

# Create a list of multimedia data
multimedia_data = [
    {
        "id": 1,
        "type": "image",
        "date": "2023-09-17",
        "location": "Bengaluru, India",
    },
    {
        "id": 2,
        "type": "video",
        "date": "2023-09-18",
        "location": "New Delhi, India",
    },
    {
        "id": 3,
        "type": "audio",
        "date": "2023-09-19",
        "location": "Mumbai, India",
    },
]

# Create a DataFrame from the list of multimedia data
multimedia_df = pd.DataFrame(multimedia_data)

# Create a list of tuples for each level of the hierarchy
levels = [["image", "video", "audio"], ["2023-09-17", "2023-09-18", "2023-09-19"], ["Bengaluru, India", "New Delhi, India", "Mumbai, India"]]

# Create a MultiIndex from the list of tuples
mi = pd.MultiIndex.from_tuples(levels, names=["type", "date", "location"])

# Set the MultiIndex as the index of the DataFrame
multimedia_df.index = mi

# Print the DataFrame
print(multimedia_df)



                                                 id   type        date  \
type             date             location                               
image            video            audio           1  image  2023-09-17   
2023-09-17       2023-09-18       2023-09-19      2  video  2023-09-18   
Bengaluru, India New Delhi, India Mumbai, India   3  audio  2023-09-19   

                                                         location  
type             date             location                         
image            video            audio          Bengaluru, India  
2023-09-17       2023-09-18       2023-09-19     New Delhi, India  
Bengaluru, India New Delhi, India Mumbai, India     Mumbai, India  
