In [ ]:
Q1. Create two 3×3 matrices using the random function in Numpy and perform the following operations.
è Product (prod)
è Multiplication (multiply)
è Dot Product (dot)


import numpy as np

A = np.random.randint(0,9,size=(3,3),dtype=int)
B = np.random.randint(0,9,size=(3,3),dtype=int)

print(A)

print(B)


A*B

In [7]:
np.multiply(A,B)

array([[ 2,  0,  6],
       [ 6, 42,  0],
       [15,  0, 15]])

In [ ]:
Q2. Perform the following set operations using the Numpy functions.
è Union
è Intersection
è Set difference
è XOR


np.dot(A,B)

In [13]:
C=np.random.randint(0,9,size=(1,4),dtype=int)
D=np.random.randint(0,9,size=(1,4),dtype=int)

print(C)
print(D)

union=np.union1d(C,D)
print(union)

[[0 1 8 8]]
[[2 3 3 3]]
[0 1 2 3 8]


In [25]:
inter=np.intersect1d(C,D)
print(inter)

[]


In [22]:
dif=np.setdiff1d(C,D)
print(diff)

[0 1 8]


In [26]:
x=np.setxor1d(C,D)
print(x)

[0 1 2 3 8]


Q3. Create a 1D array using Random function and perform the following operations.
è Cumulative sum
è Cumulative Product
è Discrete difference (with n=3)
è Find the unique elements from the array

In [36]:
E=np.random.randint(0,9,size=(1,8),dtype=int)


a=np.cumsum(E)
print(a)

[ 7 11 12 19 25 32 40 47]


In [32]:
b=np.cumprod(E)

print(b)

[     5     30    210    840   2520  20160  80640 564480]


In [35]:
c=np.diff(E,n=3)
print(c)

[[ -4   6   4 -15  16]]


In [ ]:
d=np.unique(E)
print(d)

Q4. Create two 1D array and perform the Addition using zip(), add() and user defined function (frompyfunc())


In [40]:
F=np.random.randint(0,9,size=(1,8),dtype=int)
G=np.random.randint(0,9,size=(1,8),dtype=int)

rezip=[x+y for x,y in zip(F,G)]

readd=np.add(F,G)

addfunct=np.frompyfunc(lambda x,y : x + y,2,1)
rescust= addfunct(F,G)

print(F)
print(G)
print("Using zip():",rezip)
print("using add():",readd)
print("using addfunct():",addfunct)
print("using rescust():",rescust)




[[8 7 4 2 5 3 8 6]]
[[8 6 0 4 8 7 5 3]]
Using zip(): [array([16, 13,  4,  6, 13, 10, 13,  9])]
using add(): [[16 13  4  6 13 10 13  9]]
using addfunct(): <ufunc '<lambda> (vectorized)'>
using rescust(): [[16 13 4 6 13 10 13 9]]


In [41]:
from functools import reduce
import math

def lcm(x,y):
    return x*y // math.gcd(x,y)

def gcd(x,y):
    return math.gcd(x,y)

arr=[12,18,124,36]

lcmres=reduce(lcm,arr)
gcdres=reduce(gcd,arr)

print("Array: ", arr)
print("LCM: ",lcmres)
print("GCD: ",gcdres)

Array:  [12, 18, 124, 36]
LCM:  1116
GCD:  2
